# -*- coding: utf-8 -*-
"""Untitled78.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Idcnzd_YmLuwCv5_PEMOINYeK33TBu3v
"""

# Function to add a book to the catalog
def add_book(catalog, book_id, title, author, year):
    catalog[book_id] = (title, author, year)
    print(f"Book '{title}' added.")


# Function to borrow a book
def borrow_book(catalog, borrowed_books, book_id):
    if book_id not in catalog:
        print(f"Book ID {book_id} does not exist.")
    elif book_id in borrowed_books:
        print(f"Book ID {book_id} is already borrowed.")
    else:
        borrowed_books.append(book_id)
        print(f"Book ID {book_id} borrowed successfully.")


# Function to return a book
def return_book(borrowed_books, book_id):
    if book_id in borrowed_books:
        borrowed_books.remove(book_id)
        print(f"Book ID {book_id} returned successfully.")
    else:
        print(f"Book ID {book_id} was not borrowed.")


# Function to register a member
def register_member(members, member_id):
    members.add(member_id)  # Set automatically ignores duplicates


# Function to show available books
def show_available(catalog, borrowed_books):
    print("\nAvailable Books:")
    for book_id, details in catalog.items():
        if book_id not in borrowed_books:
            title, author, year = details
            print(f"ID: {book_id}, Title: {title}, Author: {author}, Year: {year}")

def main():

    catalog = {}          # Dictionary
    borrowed_books = []   # List
    members = set()       # Set

    # Add 4 books
    add_book(catalog, 101, "Python Basics", "John Smith", 2020)
    add_book(catalog, 102, "Data Structures", "Alice Brown", 2019)
    add_book(catalog, 103, "Machine Learning", "David Lee", 2022)
    add_book(catalog, 104, "Database Systems", "Emma Wilson", 2021)

    # Register members
    register_member(members, 1)
    register_member(members, 2)
    register_member(members, 3)
    register_member(members, 2)

    print("\nRegistered Members:", members)

    # Borrow books
    borrow_book(catalog, borrowed_books, 101)
    borrow_book(catalog, borrowed_books, 103)

    # Return one book
    return_book(borrowed_books, 101)

    # Display available books
    show_available(catalog, borrowed_books)

main()