# -*- coding: utf-8 -*-
"""Untitled79.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSN8X4Gb7Bklr1Nxk4a4LNFzM52QoHnx
"""

# Part A
def add_item(item, cart=[]):
    cart.append(item)
    return cart

print(add_item("apple"))
print(add_item("banana"))
print(add_item("milk", cart=["bread"]))
print(add_item("eggs"))

# Part B
def add_item(item, cart=None):
    if cart is None:
        cart = []

    cart.append(item)
    return cart

print(add_item("apple"))
print(add_item("banana"))
print(add_item("milk", cart=["bread"]))
print(add_item("eggs"))

# part c

def create_cart(owner, discount=0):
    return {
        "owner": owner,
        "items": [],
        "discount": discount
    }


def add_to_cart(cart, name, price, qty=1):
    cart["items"].append({
        "name": name,
        "price": price,
        "qty": qty
    })

def update_price(price_tuple, new_price):

    price_tuple[0] = new_price


def calculate_total(cart):
    total = 0

    for item in cart["items"]:
        total += item["price"] * item["qty"]

    discount_amount = total * (cart["discount"] / 100)
    return total - discount_amount


def main():

    cart1 = create_cart("Aarav", 10)
    cart2 = create_cart("Priya", 5)

    add_to_cart(cart1, "Laptop", 50000, 1)
    add_to_cart(cart1, "Mouse", 500, 2)

    add_to_cart(cart2, "Book", 400, 3)

    print("Cart 1:")
    print(cart1)

    print("\nCart 2:")
    print(cart2)

    print("\nTotal Cart 1 =", calculate_total(cart1))
    print("Total Cart 2 =", calculate_total(cart2))

    price_info = (1000, "Phone")

    try:
        update_price(price_info, 1200)
    except TypeError as e:
        print("\nTuple Error:", e)


main()